openapi: 3.0.0
info:
  version: "latest"
  title: HEI - tribu
paths:
  /users:
    get:
      tags:
        - Users
      summary: get all users
      operationId: getUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'
    post:
      tags:
        - Sponsors
      summary: create sponsors
      operationId: createSponsor
      responses:
        '200':
          description: List of sponsors created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateSponsor'
  /matchs:
    get:
      tags:
        - Matchs
      summary: get all matchs
      operationId: getMatchs
      responses:
        '200':
          description: List of matchs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
    post:
      tags:
        - Matchs
      summary: create new matchs
      operationId: createMatchs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMatch'
      responses:
        '200':
          description: List of created books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
    put:
      tags:
        - Matchs
      summary: update some matchs
      operationId: updateMatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: List of updated match
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
  /match/{match_id}:
    delete:
      tags:
        - Matchs
      summary: delete a Specific match
      operationId: deleteMatch
      parameters:
        - in: path
          name: match_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Return the deleted match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
  /teams:
    get:
      tags:
        - Teams
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      tags:
        - Teams
      summary: create some teams
      operationId: createTeams
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateTeam'
      responses:
        '200':
          description: List of created Teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
    put:
      tags:
        - Teams
      summary: Update some teams
      operationId: updateTeam
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: List of updated Teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /team/{team_id}:
    delete:
      tags:
        - Teams
      summary: delete a team
      operationId: deleteTeam
      responses:
        '200':
          description: return the team deleted
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Team'
        '403':
          description: not found
  /players:
    get:
      tags:
        - Players
      summary: get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
    post:
      tags:
        - Players
      summary: create new players
      operationId: createPlayers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: List of created players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
    put:
      tags:
        - Players
      summary: update some player
      operationId: updatePlayer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdatePlayers'
      responses:
        '200':
          description: List of updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error
  /players/{player_id}:
    delete:
      tags:
        - Players
      summary: delete a Specific player
      operationId: deletePlayer
      parameters:
        - in: path
          name: player_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Return the deleted player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '403':
          description: Not found
components:
  schemas:
    CreateSponsor:
      type: object
      properties:
        name:
          type: string
    Sponsor:
      type: object
      properties:
        id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        password:
          type: string
    CreateTeam:
      type: object
      properties:
        name:
          type: string
    Team:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        players:
          type: array
          items:
            $ref: '#/components/schemas/UpdatePlayers'
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
    Match:
      type: object
      properties:
        id:
          type: number
        dateTime:
          type: string
        teamOne:
          items:
            $ref: '#/components/schemas/Team'
        teamTwo:
          items:
            $ref: '#/components/schemas/Team'
        stadium:
          type: string
        score:
          type: string
          example: 3:2
        scorers:
          items:
            $ref: '#/components/schemas/Scorers'
    Scorers:
      type: object
      properties:
        id:
          type: number
        time:
          type: string
        CSC:
          type: boolean
        team_one:
          items:
            $ref: '#/components/schemas/Player'
        team_two:
          items:
            $ref: '#/components/schemas/Player'
    CreateMatch:
      type: object
      properties:
        dateTime:
          type: string
        stadium:
          type: string
        teamOne:
          items:
            $ref: '#/components/schemas/Team'
        teamTwo:
          items:
            $ref: '#/components/schemas/Team'
    Player:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    UpdatePlayers:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        number:
          type: number
        team:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
    CreatePlayer:
      type: object
      properties:
        name:
          type: string
        number:
          type: number
        team:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string